backtest:
  end_date: '2023-06-30'
  start_date: '2022-11-11'
evaluation:
  forward_periods:
  - 1
  - 5
  - 20
  ic_threshold: 0.02
  ir_threshold: 0.3
  n_groups: 5
  quantiles: 5
factor_combination:
  weight_method: equal
factor_selection:
  correlation_threshold: 0.5
factors:
- description: "PE\u5012\u6570\u56E0\u5B50"
  fields:
  - pe_ttm
  name: pe_inv
  type: value
- description: "PB\u5012\u6570\u56E0\u5B50"
  fields:
  - pb
  name: pb_inv
  type: value
- description: "PS\u5012\u6570\u56E0\u5B50"
  fields:
  - ps_ttm
  name: ps_inv
  type: value
- description: "\u51C0\u8D44\u4EA7\u6536\u76CA\u7387"
  fields:
  - roe
  name: roe
  type: quality
- description: "\u603B\u8D44\u4EA7\u6536\u76CA\u7387"
  fields:
  - roa
  name: roa
  type: quality
- description: "\u6BDB\u5229\u7387"
  fields:
  - grossprofit_margin
  name: profit_margin
  type: quality
- description: "1\u4E2A\u6708\u52A8\u91CF"
  fields:
  - close
  name: momentum_1m
  params:
    lookback_periods:
    - 20
  type: momentum
- description: "3\u4E2A\u6708\u52A8\u91CF"
  fields:
  - close
  name: momentum_3m
  params:
    lookback_periods:
    - 60
  type: momentum
- description: "6\u4E2A\u6708\u52A8\u91CF"
  fields:
  - close
  name: momentum_6m
  params:
    lookback_periods:
    - 120
  type: momentum
- description: "1\u4E2A\u6708\u6CE2\u52A8\u7387"
  fields:
  - close
  name: volatility_1m
  params:
    window: 20
  type: volatility
- description: "3\u4E2A\u6708\u6CE2\u52A8\u7387"
  fields:
  - close
  name: volatility_3m
  params:
    window: 60
  type: volatility
other_backtest:
  benchmark: 000300.SH
  fee_rate: 0.0016
  n_stocks: 50
  rebalance_freq: week
  slippage: 0.0012
preprocessing:
  neutralization:
    enable: true
    factors:
    - market_cap
    - industry
target_factors_for_evaluation:
  fields:
  - pe_ttm
  name: pe_inv
universe:
  filters:
    min_liquidity_percentile: 0.3
    min_market_cap_percentile: 0.2
    remove_next_day_suspended: true
    remove_st: true
  index_filter:
    enable: true
    index_code: 000906.SH
