# 因子选择配置文件
# 目标因子设置（用于DataManager）
target_factors_for_evaluation:
  fields:
#    # === 规模 (Size) ===
#    - 'market_cap_log'
    - 'total_revenue_growth_yoy'
#
#    # === 价值 (Value) ===
#    - 'bm_ratio'
#    - 'ep_ratio'
#    - 'sp_ratio'
#    - 'cfp_ratio'
#
#    # === 质量 (Quality) ===
#    - 'roe_ttm'
#    - 'gross_margin_ttm'
#    - 'debt_to_assets'
#
#    # === 成长 (Growth) ===
#    - 'net_profit_growth_yoy'
#    - 'total_revenue_growth_yoy'
#
#    # === 动量 (Momentum) ===
#    - 'momentum_12_1'
#    - 'momentum_20d'
#
#    # === 风险 (Risk / Volatility) ===
#    - 'beta'
#    - 'volatility_120d'
#
#    # === 流动性 (Liquidity) ===
#    - 'turnover_rate_monthly_mean'
#    - 'liquidity_amihud'

# 回测时间范围
backtest:
  start_date: '2022-01-01'
  end_date: '2025-07-10'

# ==============================================================================
stock_pool_profiles:

  # ----------------------------------------------------------------------------
  # Profile 1: 机构标准池 (Institutional Profile)
  # 目标: 为“基本面派”和“趋势派”因子，提供一个高容量、高流动性、可实盘的“压力测试”环境。
  # 特点: 基于主流指数（如中证800），进行适度的内部流动性筛选。
  # ----------------------------------------------------------------------------
  institutional_stock_pool:
    # 启用指数过滤，
      index_filter:
        enable: true
        index_code: '000300.SH'  #

      filters:
        # --- 普适性风险过滤 (强制性) ---
        remove_st: true          # 必须剔除ST股票
        remove_new_stocks: true  # 必须剔除上市不足6个月的新股
        adapt_tradeable_matrix_by_suspend_resume: true #适配停经历复牌事件的可交易股票池

        # --- 指标过滤 (针对指数池内部) ---
        # 在中证800这个优等生群体中，再剔除流动性最差的10%，作为风险控制
        min_liquidity_percentile: 0.10

        # 中证800本身已是市值筛选的结果，此项可禁用或设为非常宽松的保险丝
        min_market_cap_percentile: 0.05

        # --- 可交易性过滤 (强制性) ---
        remove_next_day_suspended: true  # 必须剔除次日停牌
        remove_next_day_limit_up: true   # 必须剔除次日涨停

  # ----------------------------------------------------------------------------
  # Profile 2: 全市场观察池 (Full Market Observation Profile)
  # 目标: 为“市场微观派”(量价/情绪)因子，提供一个尽可能广阔，同时剔除了“数据噪音”和“交易幻影”的“淘金”环境。
  # 特点: 基于全A股，设置“地板”式的绝对风控标准。
  # ----------------------------------------------------------------------------
  microstructure_stock_pool:
    # 禁用指数过滤，使用全市场股票
      index_filter:
        enable: false
        index_code: '' # 无需指定

      filters:
        # --- 普适性风险过滤 (强制性) ---
        remove_st: true          # 必须剔除ST股票
        remove_new_stocks: true  # 必须剔除上市不足6个月的新股
        adapt_tradeable_matrix_by_suspend_resume: true #适配停经历复牌事件的可交易股票池

        # --- 指标过滤 (基于全市场) ---
        # 剔除全市场流动性最差的20%的“僵尸股”，保留真实的“散户博弈区”
        min_liquidity_percentile: 0.20

        # 剔除全市场市值最小的20%的“尘埃股”，同样是为了研究的有效性
        min_market_cap_percentile: 0.20

        # --- 可交易性过滤 (强制性) ---
        remove_next_day_suspended: true  # 必须剔除次日停牌
        remove_next_day_limit_up: true   # 必须剔除次日涨停
    # '000906.SH'  # 中证800指数代码
    # index_code: '000300.SH'  # 沪深300
    # index_code: '000905.SH'  # 中证500



# 数据预处理设置
preprocessing:
  winsorization:
    method: 'mad' # 'mad' or 'quantile'
    mad_threshold: 3.0
    quantile_range: [ 0.01, 0.99 ]
    by_industry: # 如果这个key存在，则执行分行业去极值
      primary_level: 'l2_code' # 主要使用的行业级别
      fallback_level: 'l1_code' # 回溯时使用的行业级别
      min_samples: 10 # 触发回溯的最小样本阈值 todo 有待考究
  standardization:
    method: 'zscore'
    by_industry: # 如果这个key存在，则执行分行业去极值
      primary_level: 'l2_code' # 主要使用的行业级别
      fallback_level: 'l1_code' # 回溯时使用的行业级别
      min_samples: 10 # 触发回溯的最小样本阈值 todo 有待考究

  neutralization:
    enable: true
    factors: [ 'market_cap', 'industry' ]
    by_industry:
      # 在这里明确指定要使用的行业级别！
      industry_level: 'l1_code' # 或者 'l2_code', 'l3_code'



# 因子评价设置
evaluation:
  n_groups: 5  # 分层回测的分组数
  quantiles: 5  # 分层回测的分组数
  forward_periods: [ 5,21]
#  forward_periods: [1, 5, 10, 21, 40, 60, 120]
  ic_threshold: 0.02  # IC均值阈值
  ir_threshold: 0.3  # IR阈值
  returns_calculator: ['c2c','o2c']


# 因子选择设置
factor_selection:
  correlation_threshold: 0.5  # 相关性阈值，高于此值的因子对视为高相关

# 因子合成设置
factor_combination:
  weight_method: 'equal'  # 权重方法：'equal'(等权重)或'ir'(IR加权) todo 后期改成ir加权

# 其他回测设置
other_backtest:
  rebalance_freq: 'week'  # 调仓频率: day, week, month, quarter
  n_stocks: 50  # 持仓股票数量
  fee_rate: 0.0016  # 交易费率
  slippage: 0.0012  # 滑点
  benchmark: '000300.SH'  # 基准指数


# 因子定义
  # 
  #action 如果是基础数据 比如无需计算的 那就 action: null 如果需要计算 那就action: technical_calcu
  #cal_require_base_fields_from_daily 如果依赖的require字段都是是日频级别的， 就为True 否则False


factor_definition:

  # ----------------------------------------------------------------------------
  #  一、基础数据层 (Base Data) - action: null
  #  这些是所有计算的基石，自身也可作为简单因子。
  # ----------------------------------------------------------------------------
  - name: 'close'
    style_category: 'price'
    action: null
    description: '后复权收盘价，所有价格、收益率、动量计算的基础。'
  - name: 'open'
    style_category: 'price'
    action: null
    description: '后复权开盘价。'
  - name: 'high'
    style_category: 'price'
    action: null
    description: '后复权最高价。'
  - name: 'low'
    style_category: 'price'
    action: null
    description: '后复权最低价。'
  - name: 'pct_chg'
    style_category: 'return'
    action: null
    description: '每日收益率（后复权）。'
  - name: 'total_mv'
    style_category: 'size'
    action: null
    description: '每日总市值。'
  - name: 'circ_mv'
    style_category: 'size'
    action: null
    description: '每日流通市值。'
  - name: 'turnover_rate'
    style_category: 'liquidity'
    action: null
    description: '每日换手率。'
  - name: 'pe_ttm'
    style_category: 'value'
    action: null
    description: '滚动市盈率(TTM)，基础价值指标。'
  - name: 'pb'
    style_category: 'value'
    action: null
    description: '市净率，基础价值指标。'
  - name: 'ps_ttm'
    style_category: 'value'
    action: null
    description: '滚动市销率(TTM)，基础价值指标。'
  - name: 'industry'
    style_category: 'sector'
    action: null
    description: '申万一级行业分类。'

  # ----------------------------------------------------------------------------
  #  二、衍生因子层 (Derived Factors) - action: technical_calcu / composite
  #  通过计算或合成得到，是阿尔法策略的核心。
  # ----------------------------------------------------------------------------

  # === 规模 (Size) ===
  - name: 'market_cap_log'
    style_category: 'size'
    description: '对数总市值，最经典的规模因子，用于降低市值的极端分布影响。'
    action: 'technical_calcu'
    cal_require_base_fields: ['total_mv']
    cal_require_base_fields_from_daily: True

  # === 价值 (Value) ===
  - name: 'bm_ratio'
    style_category: 'value'
    description: '账面市值比(Book-to-Market)，即市净率(PB)倒数。Fama-French三因子模型的核心成员。'
    action: 'technical_calcu'
    cal_require_base_fields: ['pb']
    cal_require_base_fields_from_daily: True
  - name: 'ep_ratio'
    style_category: 'value'
    description: '盈利收益率(Earnings Yield)，即市盈率(PE_TTM)倒数，比PE更能直接比较。'
    action: 'technical_calcu'
    cal_require_base_fields: ['pe_ttm']
    cal_require_base_fields_from_daily: True
  - name: 'sp_ratio'
    style_category: 'value'
    description: '销售收益率(Sales Yield)，即市销率(PS_TTM)倒数，对亏损的成长股有很好的评估价值。'
    action: 'technical_calcu'
    cal_require_base_fields: ['ps_ttm']
    cal_require_base_fields_from_daily: True
  - name: 'cfp_ratio'
    style_category: 'value'
    description: '现金流市值比(TTM)，衡量公司的“造血”能力相对于其市值的水平，盈利质量的试金石。'
    action: 'technical_calcu'
    cal_require_base_fields: ['cashflow_ttm', 'total_mv'] # cashflow_ttm是财报数据，total_mv是日频数据
    cal_require_base_fields_from_daily: False # 因为依赖了非日频的财报数据
  - name: 'value_composite'
    style_category: 'value'
    description: '价值合成因子，通过对bm_ratio, ep_ratio, sp_ratio等多个价值因子进行打分、标准化后再合成，旨在创建一个更稳健的价值度量。'
    action: 'composite' # 表明这是一个合成因子
    cal_require_base_fields: ['bm_ratio', 'sp_ratio', 'ep_ratio']
    cal_require_base_fields_from_daily: False # 依赖于计算后的因子

  # === 质量 (Quality) === - 【新增核心类别】
  - name: 'roe_ttm'
    style_category: 'quality'
    description: '净资产收益率(Return on Equity)，衡量公司为股东创造利润的能力，巴菲特最看重的指标之一。'
    action: 'technical_calcu'
    cal_require_base_fields: ['net_profit_ttm', 'total_equity'] # 依赖财报数据
    cal_require_base_fields_from_daily: False
  - name: 'gross_margin_ttm'
    style_category: 'quality'
    description: '销售毛利率(TTM)，反映了公司产品或服务的“护城河”和议价能力。'
    action: 'technical_calcu'
    cal_require_base_fields: ['total_revenue_ttm', 'op_cost_ttm'] # 依赖财报数据
    cal_require_base_fields_from_daily: False
  - name: 'debt_to_assets'
    style_category: 'quality'
    description: '资产负债率，衡量公司的财务杠杆和偿债风险，是稳健性的重要体现。'
    action: 'technical_calcu'
    cal_require_base_fields: ['total_debt', 'total_assets'] # 依赖财报数据
    cal_require_base_fields_from_daily: False

  # === 成长 (Growth) === - 【新增核心类别】
  - name: 'net_profit_growth_yoy'
    style_category: 'growth'
    description: '净利润同比增长率(YoY)，最直接的成长性指标。'
    action: 'technical_calcu'
    cal_require_base_fields: ['net_profit_single_q'] # 依赖单季度财报数据
    cal_require_base_fields_from_daily: False
  - name: 'total_revenue_growth_yoy'
    style_category: 'growth'
    description: '营业收入同比增长率(YoY)，衡量公司市场扩张和占有率的能力。'
    action: 'technical_calcu'
    cal_require_base_fields: ['total_revenue_single_q'] # 依赖单季度财报数据
    cal_require_base_fields_from_daily: False

  # === 动量 (Momentum) ===
  - name: 'momentum_12_1'
    style_category: 'momentum'
    description: '过去12个月剔除最近1个月的累计收益率，最经典的截面动量因子，捕捉中期价格惯性。'
    action: 'technical_calcu'
    cal_require_base_fields: ['close']
    cal_require_base_fields_from_daily: True
  - name: 'momentum_20d'
    style_category: 'momentum'
    description: '20日动量/收益率，捕捉短期趋势，常用于高频一些的策略。'
    action: 'technical_calcu'
    cal_require_base_fields: ['close']
    cal_require_base_fields_from_daily: True

  # === 风险 (Risk / Volatility) === - 【新增核心类别】
  - name: 'beta'
    style_category: 'risk'
    description: '贝塔系数，衡量个股相对于市场基准的系统性风险。（你到底是跟着别人屁股后面转，还是凭自己的真本事 （用到协同'
    action: 'technical_calcu'
    cal_require_base_fields: ['pct_chg', 'benchmark_pct_chg']
    cal_require_base_fields_from_daily: False
  - name: 'volatility_120d'
    style_category: 'risk'
    description: '120日年化波动率，衡量个股自身的价格波动风险。低波动股票有时反而有超额收益。'
    action: 'technical_calcu'
    cal_require_base_fields: ['pct_chg']
    cal_require_base_fields_from_daily: True

  # === 流动性 (Liquidity) ===
  - name: 'turnover_rate_monthly_mean'
    style_category: 'liquidity'
    description: '月平均换手率，衡量股票在一段时间内的交易活跃度。'
    action: 'technical_calcu'
    cal_require_base_fields: ['turnover_rate']
    cal_require_base_fields_from_daily: True
  - name: 'liquidity_amihud'
    style_category: 'liquidity'
    description: 'Amihud非流动性指标，衡量单位成交额能引起多大的价格波动，是冲击成本的优秀代理变量。'
    action: 'technical_calcu'
    cal_require_base_fields: ['pct_chg', 'amount'] # 依赖日收益率和成交额
    cal_require_base_fields_from_daily: True

#todo  、 大单、...