# 因子选择配置文件
# 目标因子设置（用于DataManager）
target_factors_for_evaluation:
  fields: [ 'value_composite']
# 回测时间范围
backtest:
  start_date: '2022-01-01'
  end_date: '2025-07-10'

# ==============================================================================
stock_pool_profiles:

  # ----------------------------------------------------------------------------
  # Profile 1: 机构标准池 (Institutional Profile)
  # 目标: 为“基本面派”和“趋势派”因子，提供一个高容量、高流动性、可实盘的“压力测试”环境。
  # 特点: 基于主流指数（如中证800），进行适度的内部流动性筛选。
  # ----------------------------------------------------------------------------
  institutional_stock_pool:
    # 启用指数过滤，
      index_filter:
        enable: true
        index_code: '000300.SH'  #

      filters:
        # --- 普适性风险过滤 (强制性) ---
        remove_st: true          # 必须剔除ST股票
        remove_new_stocks: true  # 必须剔除上市不足6个月的新股
        adapt_tradeable_matrix_by_suspend_resume: true #适配停经历复牌事件的可交易股票池

        # --- 指标过滤 (针对指数池内部) ---
        # 在中证800这个优等生群体中，再剔除流动性最差的10%，作为风险控制
        min_liquidity_percentile: 0.10

        # 中证800本身已是市值筛选的结果，此项可禁用或设为非常宽松的保险丝
        min_market_cap_percentile: 0.05

        # --- 可交易性过滤 (强制性) ---
        remove_next_day_suspended: true  # 必须剔除次日停牌
        remove_next_day_limit_up: true   # 必须剔除次日涨停

  # ----------------------------------------------------------------------------
  # Profile 2: 全市场观察池 (Full Market Observation Profile)
  # 目标: 为“市场微观派”(量价/情绪)因子，提供一个尽可能广阔，同时剔除了“数据噪音”和“交易幻影”的“淘金”环境。
  # 特点: 基于全A股，设置“地板”式的绝对风控标准。
  # ----------------------------------------------------------------------------
  microstructure_stock_pool:
    # 禁用指数过滤，使用全市场股票
      index_filter:
        enable: false
        index_code: '' # 无需指定

      filters:
        # --- 普适性风险过滤 (强制性) ---
        remove_st: true          # 必须剔除ST股票
        remove_new_stocks: true  # 必须剔除上市不足6个月的新股
        adapt_tradeable_matrix_by_suspend_resume: true #适配停经历复牌事件的可交易股票池

        # --- 指标过滤 (基于全市场) ---
        # 剔除全市场流动性最差的20%的“僵尸股”，保留真实的“散户博弈区”
        min_liquidity_percentile: 0.20

        # 剔除全市场市值最小的20%的“尘埃股”，同样是为了研究的有效性
        min_market_cap_percentile: 0.20

        # --- 可交易性过滤 (强制性) ---
        remove_next_day_suspended: true  # 必须剔除次日停牌
        remove_next_day_limit_up: true   # 必须剔除次日涨停
    # '000906.SH'  # 中证800指数代码
    # index_code: '000300.SH'  # 沪深300
    # index_code: '000905.SH'  # 中证500



# 数据预处理设置
preprocessing:
  neutralization:
    enable: true
    factors: [ 'market_cap', 'industry' ]



# 因子评价设置
evaluation:
  n_groups: 5  # 分层回测的分组数
  quantiles: 5  # 分层回测的分组数
  forward_periods: [ 21 ]  # 未来收益率计算的时间周期列表，单位为交易日
  ic_threshold: 0.02  # IC均值阈值
  ir_threshold: 0.3  # IR阈值

# 因子选择设置
factor_selection:
  correlation_threshold: 0.5  # 相关性阈值，高于此值的因子对视为高相关

# 因子合成设置
factor_combination:
  weight_method: 'equal'  # 权重方法：'equal'(等权重)或'ir'(IR加权) todo 后期改成ir加权

# 其他回测设置
other_backtest:
  rebalance_freq: 'week'  # 调仓频率: day, week, month, quarter
  n_stocks: 50  # 持仓股票数量
  fee_rate: 0.0016  # 交易费率
  slippage: 0.0012  # 滑点
  benchmark: '000300.SH'  # 基准指数


# 因子定义
factor_definition:
  #基本面派 (价值/成长/质量) #trend 趋势派  #microstructure（量价类因子） 微观派

  # ===============================================
  #  专题因子一：规模类 (Size) - 【毕业大考题】
  # ===============================================
  - name: 'market_cap_log'
    school: 'fundamentals'
    category_type: 'size'
    description: '总市值的自然对数，最经典、最重要的规模因子。'
    action: 'technical_calcu'
    cal_require_base_fields: [ 'circ_mv' ]
  - name: 'value_synthesizer'
    school: 'fundamentals'
    category_type: 'value'
    description: '价值合成因子。'
    action: 'technical_calcu'
    cal_require_base_fields: [ 'pe_ttm','pb','ps_ttm' ]

  - name: 'beta'
    school: 'trend' # 补充：Beta衡量的是个股与市场趋势的联动性，因此归为趋势(Trend)门派最合适。
    category_type: 'Risk' # 补充：Beta是衡量系统性风险的核心指标，属于风险(Risk)类别。
    description: '衡量个股收益率相对于市场基准（如沪深300）收益率的敏感性或波动性。通过将个股收益率对市场收益率进行线性回归得到，其斜率即为Beta值。它是衡量系统性风险的核心指标。'
    action: 'technical_calcu' # 补充：Beta的计算需要用到滚动回归，属于复杂的技术计算。
    cal_require_base_fields: [] #[ 'close', 'benchmark_close' ] # 补充：需要个股收盘价来计算其收益率，同时需要一个市场基准（如指数）的收盘价来计算市场收益率。 还是注释掉吧，我们单独自行计算！，因为raw_Dfs也拿不出benchmark_close_df 而且close也是回测周期内的，我们需要start_buffer不然又很多nana


  # ===============================================
  #  专题因子二：价值类 (Value) - 【毕业大考题】
  # ===============================================
  - name: 'pe_ttm_inv'
    school: 'fundamentals'
    category_type: 'value'
    description: '市盈率(PE_TTM)倒数，即E/P，经典的盈利收益率因子。'
    action: 'technical_calcu'
    cal_require_base_fields: [ 'pe_ttm' ]
  - name: 'pb_inv'
    school: 'fundamentals'
    category_type: 'value'
    description: '市净率 pb 倒数 '
    action: 'technical_calcu'
    cal_require_base_fields: [ 'pb' ]

  - name: 'ps_ttm_inv'
    school: 'fundamentals'
    category_type: 'value'
    description: '市销率 ps_ttm 倒数 '
    action: 'technical_calcu'
    cal_require_base_fields: [ 'ps_ttm' ]
  - name: 'value_composite'
    school: 'fundamentals'
    category_type: 'value'
    description: '价值合成因子'
    action: 'composite'
    cal_require_base_fields: [ 'ps_ttm','pe_ttm','pb' ]


  - name: 'bm_ratio'
    school: 'fundamentals'
    category_type: 'value'
    description: '账面市值比(B/M), 即市净率(PB)倒数，最经典的价值因子。'
    action: 'technical_calcu'
    cal_require_base_fields: [ 'pb' ]

  # ===============================================
  #  专题因子三：动量类 (Momentum) - 【毕业大考题】
  # ===============================================
  - name: 'momentum_20d'
    school: 'trend'
    category_type: 'momentum'
    description: '20日动量因子，计算过去20个交易日的收益率，捕捉短期趋势。'
    action: 'technical_calcu'
    cal_require_base_fields: [ 'close' ]

  # ===============================================
  #  其他：量价/微观结构类 (Microstructure)
  # ===============================================
  - name: 'turnover_rate_abnormal_20d'
    school: 'microstructure'
    category_type: 'liquidity'
    description: '20日异常换手率。用当日换手率与过去20日均值的差值，捕捉“异动”信号。'
    action: 'technical_calcu'
    cal_require_base_fields: [ 'turnover_rate' ]
  # 价值因子


  - name: 'turnover_rate_abnormal_20d'
    school: 'microstructure'
    category_type: 'liquidity'
    description: '当前换手率与过去20日均值的差值，捕捉“异常”换手情况，是更纯粹的量价信号。'
    action: 'technical_calcu'
    cal_require_base_fields: [ 'turnover_rate' ] # 需要换手率数据

  - name: 'bm_ratio'
    school: 'fundamentals'
    category_type: 'value'
    description: '市净率倒数(Book-to-Market Ratio)，经典的价值因子，衡量账面价值相对市场价值的低估程度。'
    action: 'technical_calcu'
    cal_require_base_fields: [ 'pb' ] # 需要市净率数据来计算其倒数

  - name: 'close'
    category_type: 'price'
    school: 'microstructure'
    action: null
    description: '收盘价'
    fields: [ 'close' ]


  - name: 'momentum_12_1'
    school: 'trend'
    category_type: 'trend'
    description: '过去12个月剔除最近1个月的累计收益率，经典的趋势因子，捕捉中期价格惯性。'
    action: 'technical_calcu'
    cal_require_base_fields: [ 'close' ] # 需要后复权收盘价来计算历史收益率
  - name: 'momentum_2_1'
    school: 'trend'
    category_type: 'trend'
    description: '过去2个月剔除最近1个月的累计收益率，经典的趋势因子，捕捉中期价格惯性。'
    action: 'technical_calcu'
    cal_require_base_fields: [ 'close' ] # 需要后复权收盘价来计算历史收益率

  - name: 'pct_chg'
    category_type: 'return'  # <-- 建议修改 (或者 'high_freq')
    school: 'microstructure' # 归为市场微观派是合理的，因为它直接来源于市场交易
    action: null
    description: '每日收益率（已复权）'
    fields: [ 'pct_chg' ]

  - name: 'pb'
    category_type: 'value'
    school: 'fundamentals'
    action: null
    description: '市净率（PB）'
    fields: [ 'pb' ]

  - name: 'pe_ttm'
    category_type: 'value'
    school: 'fundamentals'
    action: null
    description: 'pe滚动'
    fields: [ 'pe_ttm' ]

  - name: 'total_mv'
    category_type: 'size'
    school: 'fundamentals'
    action: null
    description: '总市值'
    fields: [ 'total_mv' ]
  - name: 'turnover_rate'
    category_type: 'liquidity'
    school: 'microstructure'
    action: null
    description: '换手率'
    fields: [ 'turnover_rate' ]

  - name: 'industry'
    category_type: 'sector'
    school: 'fundamentals'
    action: null
    description: '行业分类'
    fields: [ 'industry' ]

  - name: 'circ_mv'
    category_type: 'size'
    school: 'fundamentals'
    action: null
    description: '流通市值'
    fields: [ 'circ_mv' ]

  - name: 'list_date'
    category_type: 'metadata'
    school: 'fundamentals'
    action: null
    description: '上市日期'
    fields: [ 'list_date' ]
  - name: 'open'
    category_type: 'price'
    school: 'microstructure'
    action: null
    description: '开盘价'
    fields: [ 'open' ]
  - name: 'high'
    category_type: 'price'
    school: 'microstructure'
    action: null
    description: '最高价'
    fields: [ 'high' ]

  - name: 'low'
    category_type: 'price'
    school: 'microstructure'
    action: null
    description: '最低价'
    fields: [ 'low' ]

  - name: 'pre_close'
    category_type: 'price'
    school: 'microstructure'
    action: null
    description: '前收盘价'
    fields: [ 'pre_close' ]

#todo 成长类因子、 大单、...